language: python
sudo: false

matrix:
  include:
    # Miscellaneous Builds
    - python: 3.6
      env: TOXENV=lint
    - python: 3.6
      env: TOXENV=packaging

    # Linux Builds
    - python: 2.6
      env: TOXENV=py26
    - python: 2.7
      env: TOXENV=py27
    - python: 3.3
      env: TOXENV=py33
    - python: 3.4
      env: TOXENV=py34
    - python: 3.5
      env: TOXENV=py35
    - python: 3.6
      env: TOXENV=py36
    - python: nightly
      env: TOXENV=py37

cache:
  - pip
  - directories:
    - ${HOME}/.cache

install:
  - pip install tox

script:
  - tox

after_success:
  - source .tox/${TOXENV}/bin/activate
  - pip install codecov
  - codecov --env TRAVIS_OS_NAME,TOXENV

notifications:
  email: false
